# Generated by Django 3.2 on 2021-05-09 10:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Name')),
                ('text', models.TextField(default='', max_length=280, verbose_name='Text')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('like_count', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Updated DateTime')),
            ],
            options={
                'db_table': 'tweet',
            },
        ),
    ]
